config/routes.rb
Productapp::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'current_user', to: 'users#show', as: 'current_user'
  get 'settings', to: 'usersedit', as: 'users_edit'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

  resources :users
  resources :sessions
  resources :products do 
    resources :comments
    member { post :vote }
  end

  root :to => 'products#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  has_reputation :avg_rating,
    :source => :user,
    :aggregated_by => :average,
    :source_of => [{ :reputation => :review_skill, :of => :user }]

  def content_safe
    content.gsub(/([ ])/)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def index
    @comments = @commentable.comments
  end

  def comment
   @products = Product.find_with_reputation(:votes, :all, order: "votes desc")
  end

  def new
    @comment = @commentable.comments.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @commentable, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
  
  def create
    @comment = @commentable.comments.new(params[:comment])
    @comment.user = current_user
    if @comment.save
      redirect_to @commentable, notice: "Comment created"
    else
      render :new
    end
  end

  private

  def load_commentable
    klass = [Product].detect { |c| params["#{c.name.underscore}_id"] }
    @commentable = klass.find(params["#{klass.name.underscore}_id"])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<table class="table table-striped">
  <% @comments.each do |comment| %>

    <tr>
      <td>
        <div class="media">
          <a class="pull-left" href="#">
            <% if comment.user.image_url %>
              <%= image_tag comment.user.image_url(:comment).to_s, class: "media-object" %>
            <% else %>
              <%= image_tag 'blank.png', :size => '36x36' %>
            <% end %>
          </a>
          <div class="media-body">
             <h5 class="media-heading">
              <%= link_to comment.user.name, comment.user %>
            </h5>
           
              <%= comment.content.html_safe %>
            <div class="media">
            </div>
          </div>
        </div>

        <div class="pull-left">
          <% if can? :manage, comment %>
            <%= link_to "Edit", [:edit, @commentable, comment] %>
          <% end %>
        </div>
    </td>
  </tr>
  
  <% end %>
</table>

app/views/comments/_form.html.erb
 <% if current_user.image_url %>
   <%= image_tag current_user.image_url(:comment).to_s, class: "img-rounded" %>
 <% else %>
   <%= image_tag 'blank.png', :size => '36x36' %>
 <% end %>

 <b><%= link_to current_user.name, current_user %></b>

<%= form_for [@commentable, @comment] do |f| %>
    <%= f.text_area :content, rows: 5,placeholder: "Write a comment...", class: "span7" %>
    <%= f.submit :class => "btn btn-blue btn-mini" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= render 'comments' %>

<p><%= link_to "New Comment", new_product_comment_path(@commentable) %></p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>