config/routes.rb
Productapp::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'current_user', to: 'users#show', as: 'current_user'
  get 'settings', to: 'usersedit', as: 'users_edit'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

  resources :users
  resources :sessions
  resources :products do 
    resources :comments
    member { post :vote }
  end

  root :to => 'products#index'

end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not Logged In" if current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def body_class(klass)
    content_for(:body_class) do
      klass
    end    
  end

  def body_id(id)
    content_for(:body_id) do
      id
    end
  end
end

app/views/application/_topbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <ul class="nav pull-left">
        <%= link_to "Ratify", root_path, class:"brand" %>
      </ul>


        <% if current_user %>
            <ul class="nav pull-right">
              <ul class="nav secondary-nav">
                <li class="dropdown">
                  <a href="" class="dropdown-toggle" data-toggle="dropdown">
                    <% if current_user.image_url %>
                      <%= image_tag current_user.image_url(:avatar).to_s %>
                    <% else %>
                      <%= image_tag 'blank.png', :size => '18x18' %>
                    <% end %>
                    <%= current_user.name %>
                    <i class="caret"></i>
                  </a>
                  
                  <ul class="dropdown-menu pull-right">
                    <li><%= link_to content_tag(:i, nil, class: "icon-upload") + " New Beer", new_product_path %></li>
                    <li><%= link_to content_tag(:i, nil, class: "icon-user")+ " Your Beers", current_user_path%></li>
                    <li><%= link_to content_tag(:i, nil, class: "icon-cog")+ " Settings", edit_user_path(current_user)%></li>
                    <li><%= link_to content_tag(:i, nil, class: "icon-off")+ " Log Out", logout_path %></li>
                  </ul>
                </li>
              </ul>
            </ul>
        <% end %>


        <ul class="nav pull-right">
          <li class="active"><%= link_to content_tag(:i, nil, class: "icon-home") + " Home", root_path %></li>
            <% if current_user.nil? %>  
              <li><%= link_to content_tag(:i, nil, class: "icon-user") + " Login", login_path %></li>
            <% end %>  
          </li>
        </ul>

  </div>
</div>
</div>