config/routes.rb
Productapp::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'current_user', to: 'users#show', as: 'current_user'
  get 'settings', to: 'usersedit', as: 'users_edit'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

  resources :users
  resources :sessions
  resources :products do 
    resources :comments
    member { post :vote }
  end

  root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :image, :brewery
  has_many :comments, as: :commentable
  belongs_to :user
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  has_reputation :votes, :source => :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    @products = Product.find_with_reputation(:votes, :all, order: "votes desc", limit: 10)
    #@products.each do |product|
      #@commentone = product.comments.first
      #@commenttwo = product.comments.second
    #end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json

  def show
    @product = Product.find(params[:id])
    @commentable = @product
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.create!(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product } else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @product = Product.find(params[:id])
    @product.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thanks you for voting!"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
   <br />

   <div class="field">
    <%= f.label :brewery %>
    <%= f.text_field :brewery %>
   </div>
   <br />

      <%= f.label :image %>
    <% if @product.image_url %>
      <%= image_tag @product.image_url(:upload).to_s %>
    <% else %>
      <%= image_tag 'blank.png' %>
    <% end %>
      <%= f.file_field :image %>
  <br />
  <br />

    <div class="field">
      <%= f.label "Commercial Description" %>
      <%= f.text_area :description, rows: 5,placeholder: "Write a description...", class: "span7" %>
    </div>
  <br />

    <div class="field">
      <%= f.label :price %>
      <%= f.number_field :price %>
    </div>
  <br />

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/products/_product.html.erb
<div class="container">
  <% @products.each do |product| %>
      <div class="span3">


      <%= link_to (image_tag product.image_url(:thumb).to_s), product, :class=> 'thumbnail' %>

      <div class="row">
        <p class="text-center"><%= link_to product.name, product %></p>
      </div>

    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% body_class "index" %>
 <% body_id "product" %>

  <%= render 'product' %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <h2><%= @product.name %></h2>
</p>

<p>
  <b>Brewed by</b>
  <%= @product.brewery %>
<p>
  <%= image_tag @product.image_url(:upload).to_s %>
</p>

<div class="span4">
  <h4>Commercial Description</h4>
  <%= @product.description %>
</div>

<% if can? :manage, @product %>
  <%= link_to 'Edit', edit_product_path(@product) %>
  | <%= link_to 'Destroy', @product, :confirm => 'Are you sure?', :method => :delete %> 
<% end %> 


<legend>Comments</legend>

<% if current_user %>
  <%= render "comments/form" %>
<% end %>

<%= render "comments/comments" %>